### PR TITLE
Added translations for Send Test Mail feature

### PR DESCRIPTION
**Pull request by askvortsov1**
Companion PR to https://github.com/flarum/core/pull/2023

### CODE REVIEW

**Comment by rob006** [comment]
> Please sort keys alphabetically!

This requirement is really annoying for translators. Order of strings may give some hints about the context for specific phrase. Forcing alphabetical order is just more work for devs to create less useful resource...

**Comment by franzliedke** [comment]
@rob006 I understand your concern, but want to provide some nuance:
- Ordering alphabetically is the only sensible, objective way of having consistency in a language file (and we even had an automatic linter for a while enforcing this, IIRC). Since this is a place that is touched by almost everyone changing or adding new features, any other "convention" for ordering is bound to be pointless and things will devolve into a mess. I've seen this happen.
- We try to provide a bit of context through nesting and inline comments. A *lot* of thought went into this overall structure, trust me.

It's a trade-off, as with many things. So far, I personally have been very happy with it.

**Comment by rob006** [comment]
> Ordering alphabetically is the only sensible, objective way of having consistency in a language file

It is not the only one, it is just the simplest one. Ordering by file name and line number is also consistent, but in addition it is also natural (it is common convection for extractors generating pot files).

It is also debatable whether you need convention here at all. This file is created by humans for humans, why do you need to follow rule typical for machines? You don't order methods in your classes alphabetically...

> So far, I personally have been very happy with it.

I'm guessing you're not using these files. :P

**Comment by askvortsov1** [comment]
Resolved by moving the translations to the api section, where they belong (this section is for emails that are sent only). I left subject before body, as that is the convention with the rest of these.

**Pull request merged**
