### PR TITLE
Improved style of English

### PR DESCRIPTION
**Pull request by fvlasie**

### CODE REVIEW

**Comment by tobscure** [comment]
Thanks for the PR @fvlasie. Do you have some kind of justification for this change? I'm not sure it's necessary, "It looks like" appears more natural to me.

**Comment by franzliedke** [comment]
It seems *as though* the suggestion is correct:
- http://www.grammarerrors.com/grammar/likeas-thoughas-if/
- http://cliffordgarstang.com/tips-for-writers-like-vs-as-if/

Unless we're *trying* to be colloquial, the PR should be merged IMO. Your choice, @tobscure.

**Comment by fvlasie** [comment]
If want to use the word "like", you could say something like :) "It looks like an empty discussion!" or "It looks like a quiet conversation."

**Comment by luceos** [comment]
Thank you, picking this up for beta 9.

**Pull request merged**
