### PR TITLE
added the label to the new 'follow new discussions' preference

### PR DESCRIPTION
**Pull request by oscarotero**
Related: https://github.com/flarum/flarum-ext-subscriptions/pull/9

### CODE REVIEW

**Comment by dcsjapan** [comment]
@tobscure This looks fine in that the key name matches `forum_follow_after_reply_label` from https://github.com/flarum/flarum-ext-english/pull/57 ... 

... But I'm not sure what the `forum_` signifies in either case. Could these two keys do without that?

**Comment by tobscure** [comment]
@dcsjapan Right, the `forum_` prefix is unnecessary.

**Comment by dcsjapan** [comment]
I'll send a PR to remove both once you've merged this. 😄

**Comment by tobscure** [comment]
Thanks! This one isn't actually going to get merged for now due to issues in its counterpart, flarum/flarum-ext-subscriptions#9 (with additional discussion in flarum/core#768). But a PR for the other one would be greatly appreciated :)

**Comment by franzliedke** [comment]
Closing, see https://github.com/flarum/core/issues/768#issuecomment-554558814.

**Pull request closed without merging**
