### PR TITLE
Add new password rule language line

### PR DESCRIPTION
**Pull request by qiaeru**
See: https://github.com/laravel/laravel/commit/050c1d880ec1d48ef40d7a0f2b2f1040c23cebb9

### CODE REVIEW

**Comment by datitisev** [comment]
This is only used in Laravel v6.2 and later. Flarum currently uses Laravel v5.7, and future plans about updating to v6 are unknown, so this line won't be used at all for the time until that happens.

**Comment by milescellar** [comment]
Laravel 6.x lines are already included, so I don't see why we shouldn't include this one (or we should remove other lines?).

**Comment by datitisev** [comment]
Unless I'm seeing this wrong, the line won't be used until we update to Laravel v6.2+. Not sure what other lines you are talking about in `validation.yml` being from v6 as well.

The only one I can see that wouldn't be used is `ends_with` (https://github.com/flarum/lang-english/commit/90a31d5a9aea1459686d6fbe19193fd31994179d#diff-b5ad83ac7ad86785dd4ae21aee5bf015) as that was added in v5.8, and we use v5.7.

**Comment by milescellar** [comment]
You're correct, I hadn't seen the compatibilities.

`ends_with` starts with 5.8.17 and `password` starts with 6.2.0.

**Comment by qiaeru** [comment]
Bump. Flarum uses Laravel 6 now, am I wrong?

https://github.com/flarum/core/commit/9c09fe846515b45bf65033132908cd8fecea6eb9

**Comment by franzliedke** [comment]
Thanks :pray:

**Pull request merged**
