### PR TITLE
Fix sorting

### PR DESCRIPTION
**Pull request by qiaeru**

### CODE REVIEW

**Comment by Littlegolden** [comment]
I think the original order is quite good, first tell the translator what the subject is, and then is the specific email content of the subject.

**Comment by qiaeru** [comment]
I agree with you, but if a validation tool is used in the future to ensure that alphabetical sorting is respected, these strings are not properly sorted. [There is a tool for that for translators](https://github.com/sijad/yaml-translation-utils), so some can use it to validatate a language pack (like me).

**Comment by rob006** [comment]
@qiaeru Why would you need to use a tool for ensuring order of strings? Order is irrelevant from Flarum perspective.

**Comment by Littlegolden** [comment]
Maybe it's like your translation tool? Create a branch of the translation file collection and sort all the lines in alphabetical order.

**Comment by rob006** [comment]
But why sort in this case? Original order could be used for these files.

**Comment by Littlegolden** [comment]
That's the point, maybe he skipped the branch phase and went straight to the translation work via synced the source translation file.

**Comment by franzliedke** [comment]
This is intentional. From [our docs](https://docs.flarum.org/extend/i18n.html#naming-identifier-keys):

>  ID keys should be arranged in alphabetical order within each namespace, so they'll be easy for developers to find. (There is one exception to this rule! ID keys in the `email` namespace should be listed just as they appear in your mail client: `subject` first, then `body`.)

**Pull request closed without merging**
