### PR TITLE
Move locale files from language pack to extensions

### PR DESCRIPTION
**Pull request by rob006**
Fixes https://github.com/flarum/core/issues/2090

This changes English language pack into simple stub that does not have any translations (all related translations are in respective packages), but only enables English language in forum. This should:
1. Simplify development (no need for 2 PR to add new feature).
2. Make English fallback for untranslated strings work also when English language pack is disabled/not installed. In most cases it should also prevent this from happening:

5e66f2fd

Dependencies:

- [ ] https://github.com/flarum/mentions/pull/56
- [ ] https://github.com/flarum/akismet/pull/17
- [ ] https://github.com/flarum/tags/pull/99
- [ ] https://github.com/flarum/flags/pull/32
- [ ] https://github.com/flarum/emoji/pull/32
- [ ] https://github.com/flarum/suspend/pull/28
- [ ] https://github.com/flarum/subscriptions/pull/34
- [ ] https://github.com/flarum/sticky/pull/21
- [ ] https://github.com/flarum/statistics/pull/13
- [ ] https://github.com/flarum/pusher/pull/26
- [ ] https://github.com/flarum/markdown/pull/21
- [ ] https://github.com/flarum/lock/pull/24
- [ ] https://github.com/flarum/likes/pull/23
- [ ] https://github.com/flarum/approval/pull/22
- [ ] https://github.com/flarum/nicknames/pull/3
- [ ] https://github.com/flarum/core/pull/2408

### CODE REVIEW

**Comment by askvortsov1** [comment]
@rob006 we've discussed this internally and are ready to proceed, sorry for the delay in acting on this. Could you update the core and tags PRs to reflect changes made since this was opened?

**Comment by rob006** [comment]
I'll try to do it this evening or tomorrow. There is also a new extension to move (nicknames).

**Comment by askvortsov1** [comment]
Thank you so much for bearing with us on this!

**Comment by rob006** [comment]
@askvortsov1 Done.

**Comment by rob006** [comment]
@askvortsov1 I think you missed https://github.com/flarum/nicknames/pull/3

**Comment by askvortsov1** [comment]
I did, thanks for finding that :D

**Comment by qiaeru** [comment]
How this affects other language packs?

By the way, with this change, translators cannot follow changes/commits easily. 😟

**Comment by askvortsov1** [comment]
> How this affects other language packs?
> 
> By the way, with this change, translators cannot follow changes/commits easily.

Important question, but could you put it in https://github.com/flarum/core/issues/2090, which is the global issue for discussion?

**Comment by rob006** [comment]
@qiaeru AFAIK it does not affect other language packs at all. While it indeed may make it harder to sync changes, core extensions are only part of the ecosystem and most of installations will use also other community extensions, so to make useful language pack you need to cover also other translations that were never available in this repository. I highly recommend to take a look at https://discuss.flarum.org/d/20807-simplify-translation-process-with-weblate. You can also track all changes in https://github.com/rob006-software/flarum-translations/tree/master/sources - there should all changes in translations of any popular extension.

**Pull request merged**
